modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://www.github.com/spazzylemons/ToasterSimulator/issues/"

[[mods]]
modId="toastersimulator"
version="${file.jarVersion}"
displayName="Toaster Simulator"
displayURL="https://www.github.com/spazzylemons/ToasterSimulator/"
# logoFile="logo.png"
authors="spazzylemons"
description='''
toasters
'''

[[dependencies.toastersimulator]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toastersimulator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
